### ISSUE TITLE
Creating and submitting a modal is successful, but error thrown in console.

### ISSUE THREAD

**Issue by trjo1016** [Mateo-tem/discord-modals#114]
Hello Developers,

while working with modalSubmit, I encountered a kind of annoying issue when submitting a normal modal embedded in a message.
The result is a normal looking modal execution:
![image](https://user-images.githubusercontent.com/81167386/185479402-12a15ea0-942e-4187-b530-34509930e615.png)

but it doesn't fit with the console log (edited out private stuff):

```
MyConsole: Waiting for modalSubmit 
MyConsole: <@66...51> created a reactions poll 
SHOW_MODAL_ERROR: An error occurred when showing a modal. DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute ([mypath]\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push ([mypath]\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async showModal ([mypath]\node_modules\discord-modals\src\structures\ShowModal.js:56:3) {
  method: 'post',
  path: '/interactions/10...14/aW50ZXJhY3Rpb246MTA...0dFa1BJNXRaSVdNYzlIb3FGQ3FQNmRpbGJKVkFIRUttTThGclEwZEJVVUNOTWtaYUN1Sm95SXhEVw/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 9, data: [Object] }, files: [] }
}
MyConsole: Waiting for modalSubmit`
```

I'm using discord v13 with the SapphireClient. If you have any idea what I could do about it, I would appreciate any answer to that. :)

Here is my source code:

````
client.on('interactionCreate', (interaction) => {
                    if (interaction.member.user.bot || !interaction.isButton) return;
                    showModal(modal, {
                        client,
                        interaction
                    }).then(() => log.console('Waiting for modalSubmit'))
                })


                client.on('modalSubmit', async (modal) => {
                    if (modal.customId === 'pollModal') {
                        const fields = modal.fields.slice()
                        const questionResponse = fields.shift().value
                        const reactions = ['1️⃣', '2️⃣', '3️⃣', '4️⃣']
                        const embedFields = []
                        fields.forEach(field => embedFields.push({
                            name: '\u200b',
                            value: `${reactions.shift()} ${field.value}`,
                            inline: false
                        }))

                        const pollEmbed = new MessageEmbed()
                            .setTitle(questionResponse)
                        pollEmbed.addFields(...embedFields)
                        channel.send({ embeds: [pollEmbed] })
                        await modal.deferReply({ ephemeral: true }).then(() => log.console(`${author} created a reactions poll`))
                        modal.followUp({ content: 'Poll successfully created.', ephemeral: true })
                        done = true
                    }
                })

                client.ws.on('INTERACTION_CREATE', (data) => {
                    if (!data.type) return;
                    if (data.type == 5) {
                        client.emit('modalSubmit', new ModalSubmitInteraction(client, data))
                    } else return;
                })

**Comment by trjo1016** [comment]
nvm both the interactioncreate events go at the same time, when I submit the modal. I set the first (lowercase) interactioncreate event at 'once', error doesn't occur anymore

**Comment by trjo1016** [comment]
I have a suggestion
