### ISSUE TITLE
Error [INVALID_CLIENT]: The provided Client is invalid in this context.

### ISSUE THREAD

**Issue by xTurbo21** [Mateo-tem/discord-modals#17]
So I did everything as the docs said but I don't know why I'm getting this error:

```/home/runner/Waiter/node_modules/discord-modals/index.js:14
  if (!(client instanceof Client)) throw new Error('INVALID_CLIENT');
                                   ^

Error [INVALID_CLIENT]: The provided Client is invalid in this context.
    at module.exports (/home/runner/Waiter/node_modules/discord-modals/index.js:14:42)
    at Object.<anonymous> (/home/runner/Waiter/index.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'INVALID_CLIENT'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Waiter@1.1.5 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Waiter@1.1.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-01T13_16_40_246Z-debug.log
exit status 1
```

Why is this happening? This is my main (index.js) file:

```
const express = require('express')
const app = express()
app.listen(8080)
app.get('/', (req, res) => {
  res.send('Waiter is online!')
})


const { Client, Collection } = require("discord.js")
const client = new Client({ intents: 32767 })
const discordModals = require('discord-modals')
discordModals(client);

client.commands = new Collection();
client.filters = new Collection();
client.filtersLog = new Collection();
client.voiceGenerator = new Collection();
client.cooldowns = new Collection();

require("./Systems/GiveawaySys")(client);
require("./Handlers/Events")(client);
require("./Handlers/Commands")(client);

client.login(process.env.token);
```

I run it in replit so I have the express function above.

**Comment by Mateo-tem** [comment]
What version of discord.js are you using?

**Comment by xTurbo21** [comment]
> What version of discord.js are you using?

13.6.0
![image](https://user-images.githubusercontent.com/50515196/156201893-a0deb41d-653f-4bf9-89ee-437970941f4d.png)

**Comment by Mateo-tem** [comment]
And if you put this, below of `const client = new Client({ intents: 32767 })`?
```javascript
console.log(client)
```

**Comment by xTurbo21** [comment]
> And if you put this, below of `const client = new Client({ intents: 32767 })`?
> 
> ```js
> console.log(client)
> ```

Sends a huge log:

```
<ref *1> Client {
  _events: [Object: null prototype] { shardDisconnect: [Function (anonymous)] },
  _eventsCount: 1,
  _maxListeners: undefined,
  options: {
    intents: 32767,
    waitGuildTimeout: 15000,
    shardCount: 1,
    makeCache: [Function (anonymous)],
    messageCacheLifetime: 0,
    messageSweepInterval: 0,
    invalidRequestWarningInterval: 0,
    partials: [],
    restWsBridgeTimeout: 5000,
    restRequestTimeout: 15000,
    restGlobalRateLimit: 0,
    retryLimit: 1,
    restTimeOffset: 500,
    restSweepInterval: 60,
    failIfNotExists: true,
    userAgentSuffix: [],
    presence: { status: 'online', user: [Object] },
    sweepers: {},
    ws: {
      large_threshold: 50,
      compress: false,
      properties: [Object],
      version: 9
    },
    http: {
      agent: {},
      version: 9,
      api: 'https://discord.com/api',
      cdn: 'https://cdn.discordapp.com',
      invite: 'https://discord.gg',
      template: 'https://discord.new',
      scheduledEvent: 'https://discord.com/events'
    },
    shards: [ 0 ]
  },
  rest: RESTManager {
    client: [Circular *1],
    handlers: Collection(0) [Map] {},
    versioned: true,
    globalLimit: Infinity,
    globalRemaining: Infinity,
    globalReset: null,
    globalDelay: null,
    sweepInterval: Timeout {
      _idleTimeout: 60000,
      _idlePrev: [TimersList],
      _idleNext: [TimersList],
      _idleStart: 1184,
      _onTimeout: [Function (anonymous)],
      _timerArgs: undefined,
      _repeat: 60000,
      _destroyed: false,
      [Symbol(refed)]: false,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 8,
      [Symbol(triggerId)]: 1
    }
  },
  _cleanups: Set(1) { [Function: bound ] },
  _finalizers: FinalizationRegistry {},
  ws: WebSocketManager {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    gateway: null,
    totalShards: 1,
    shards: Collection(0) [Map] {},
    status: 3,
    destroyed: false,
    reconnecting: false,
    [Symbol(kCapture)]: false
  },
  actions: ActionsManager {
    client: [Circular *1],
    ChannelCreate: ChannelCreateAction { client: [Circular *1] },
    ChannelDelete: ChannelDeleteAction { client: [Circular *1], deleted: Map(0) {} },
    ChannelUpdate: ChannelUpdateAction { client: [Circular *1] },
    GuildBanAdd: GuildBanAdd { client: [Circular *1] },
    GuildBanRemove: GuildBanRemove { client: [Circular *1] },
    GuildChannelsPositionUpdate: GuildChannelsPositionUpdate { client: [Circular *1] },
    GuildDelete: GuildDeleteAction { client: [Circular *1], deleted: Map(0) {} },
    GuildEmojiCreate: GuildEmojiCreateAction { client: [Circular *1] },
    GuildEmojiDelete: GuildEmojiDeleteAction { client: [Circular *1] },
    GuildEmojiUpdate: GuildEmojiUpdateAction { client: [Circular *1] },
    GuildEmojisUpdate: GuildEmojisUpdateAction { client: [Circular *1] },
    GuildIntegrationsUpdate: GuildIntegrationsUpdate { client: [Circular *1] },
    GuildMemberRemove: GuildMemberRemoveAction { client: [Circular *1] },
    GuildMemberUpdate: GuildMemberUpdateAction { client: [Circular *1] },
    GuildRoleCreate: GuildRoleCreate { client: [Circular *1] },
    GuildRoleDelete: GuildRoleDeleteAction { client: [Circular *1] },
    GuildRoleUpdate: GuildRoleUpdateAction { client: [Circular *1] },
    GuildRolesPositionUpdate: GuildRolesPositionUpdate { client: [Circular *1] },
    GuildScheduledEventCreate: GuildScheduledEventCreateAction { client: [Circular *1] },
    GuildScheduledEventDelete: GuildScheduledEventDeleteAction { client: [Circular *1] },
    GuildScheduledEventUpdate: GuildScheduledEventUpdateAction { client: [Circular *1] },
    GuildScheduledEventUserAdd: GuildScheduledEventUserAddAction { client: [Circular *1] },
    GuildScheduledEventUserRemove: GuildScheduledEventUserRemoveAction { client: [Circular *1] },
    GuildStickerCreate: GuildStickerCreateAction { client: [Circular *1] },
    GuildStickerDelete: GuildStickerDeleteAction { client: [Circular *1] },
    GuildStickerUpdate: GuildStickerUpdateAction { client: [Circular *1] },
    GuildStickersUpdate: GuildStickersUpdateAction { client: [Circular *1] },
    GuildUpdate: GuildUpdateAction { client: [Circular *1] },
    InteractionCreate: InteractionCreateAction { client: [Circular *1] },
    InviteCreate: InviteCreateAction { client: [Circular *1] },
    InviteDelete: InviteDeleteAction { client: [Circular *1] },
    MessageCreate: MessageCreateAction { client: [Circular *1] },
    MessageDelete: MessageDeleteAction { client: [Circular *1] },
    MessageDeleteBulk: MessageDeleteBulkAction { client: [Circular *1] },
    MessageReactionAdd: MessageReactionAdd { client: [Circular *1] },
    MessageReactionRemove: MessageReactionRemove { client: [Circular *1] },
    MessageReactionRemoveAll: MessageReactionRemoveAll { client: [Circular *1] },
    MessageReactionRemoveEmoji: MessageReactionRemoveEmoji { client: [Circular *1] },
    MessageUpdate: MessageUpdateAction { client: [Circular *1] },
    PresenceUpdate: PresenceUpdateAction { client: [Circular *1] },
    StageInstanceCreate: StageInstanceCreateAction { client: [Circular *1] },
    StageInstanceDelete: StageInstanceDeleteAction { client: [Circular *1] },
    StageInstanceUpdate: StageInstanceUpdateAction { client: [Circular *1] },
    ThreadCreate: ThreadCreateAction { client: [Circular *1] },
    ThreadDelete: ThreadDeleteAction { client: [Circular *1] },
    ThreadListSync: ThreadListSyncAction { client: [Circular *1] },
    ThreadMemberUpdate: ThreadMemberUpdateAction { client: [Circular *1] },
    ThreadMembersUpdate: ThreadMembersUpdateAction { client: [Circular *1] },
    TypingStart: TypingStart { client: [Circular *1] },
    UserUpdate: UserUpdateAction { client: [Circular *1] },
    VoiceStateUpdate: VoiceStateUpdate { client: [Circular *1] },
    WebhooksUpdate: WebhooksUpdate { client: [Circular *1] }
  },
  voice: ClientVoiceManager { adapters: Map(0) {} },
  shard: null,
  users: UserManager {},
  guilds: GuildManager {},
  channels: ChannelManager {},
  sweepers: Sweepers {
    options: {},
    intervals: {
      applicationCommands: null,
      bans: null,
      emojis: null,
      invites: null,
      guildMembers: null,
      messages: null,
      presences: null,
      reactions: null,
      stageInstances: null,
      stickers: null,
      threadMembers: null,
      threads: null,
      users: null,
      voiceStates: null
    }
  },
  presence: ClientPresence {
    userId: null,
    guild: null,
    status: 'online',
    activities: [],
    clientStatus: null
  },
  user: null,
  application: null,
  readyAt: null,
  [Symbol(kCapture)]: false
}
```

**Comment by Mateo-tem** [comment]
Maybe is a bug, will be solved in the next version. **Thanks to report it!**

**Comment by xTurbo21** [comment]
> Maybe is a bug, will be solved in the next version. **Thanks to report it!**

okayy thanks, I'll wait I guess
