### ISSUE TITLE
More than 5 Components

### ISSUE THREAD

**Issue by dubfib** [Mateo-tem/discord-modals#53]
It says I need 1 - 5 components, is there a way I can get more? I need about 7 or more.

Error:
```js
SHOW_MODAL_ERROR: An error occurred when showing a modal. DiscordAPIError: Invalid Form Body
data.components: Must be between 1 and 5 in length.
    at RequestHandler.execute (/var/lib/pufferpanel/servers/1d8d04a2/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/var/lib/pufferpanel/servers/1d8d04a2/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async showModal (/var/lib/pufferpanel/servers/1d8d04a2/node_modules/discord-modals/src/structures/ShowModal.js:49:9) {
  method: 'post',
  path: '/sorry/but/no',
  code: 50035,
  httpStatus: 400,
  requestData: { json: { type: 9, data: [Object] }, files: [] }
}
```

Code:
```js
const { MessageEmbed, Formatters } = require('discord.js');

const { Modal, TextInputComponent, showModal } = require('discord-modals');

const fetch = require('node-fetch');
const db = require('quick.db');

module.exports = {
    category: 'Discord',
    description: 'Apply for The Damned Guild!',
    
    slash: true,
    testOnly: true,
    
    callback: async ({ client, interaction, args }) => {
        const modal = new Modal()
        .setCustomId('modal-apply')
        .setTitle('Guild Application')
        
          .addComponents([
           new TextInputComponent()
           .setCustomId('textinput-ign')
           .setLabel("➩ What's you Minecraft IGN?")
           .setStyle('SHORT')
           .setMinLength(4)
           .setMaxLength(10)
           .setRequired(true)
           .setPlaceholder('Example: Lvnnaa')
          ])
        
          .addComponents([
            new TextInputComponent()
            .setCustomId('textinput-age')
            .setLabel("➩ What's your age? (Requirement: 13+)")
            .setStyle('SHORT')
            .setMinLength(4)
            .setMaxLength(10)
            .setRequired(true)
            .setPlaceholder('You must be 13+')
          ])

          .addComponents([
            new TextInputComponent()
            .setCustomId('textinput-joindamned')
            .setLabel("➩ Why do you want to join The Damned?")
            .setStyle('SHORT')
            .setMinLength(4)
            .setMaxLength(10)
            .setRequired(true)
            .setPlaceholder('Example: I want join because _______.')
          ])

          .addComponents([
            new TextInputComponent()
            .setCustomId('textinput-guilds')
            .setLabel("➩ What guilds were you previously in?")
            .setStyle('SHORT')
            .setMinLength(4)
            .setMaxLength(10)
            .setRequired(true)
            .setPlaceholder("If you haven't just say no")
          ])

         .addComponents([
            new TextInputComponent()
            .setCustomId('textinput-callyou')
            .setLabel("➩ What would you like us to call you?")
            .setStyle('SHORT')
            .setMinLength(4)
            .setMaxLength(10)
            .setRequired(true)
            .setPlaceholder("Example: Luna")
         ])
          
        .addComponents([
             new TextInputComponent()
            .setCustomId('textinput-pronouns')
            .setLabel("➩ What are your pronouns?")
            .setStyle('SHORT')
            .setMinLength(4)
            .setMaxLength(10)
            .setRequired(true)
            .setPlaceholder("Example: they/them, he/him, she/her")
        ])
        
        .addComponents([
            new TextInputComponent()
            .setCustomId('textinput-main')
            .setLabel("➩ What do you mostly main on Hypixel?")
            .setStyle('SHORT')
            .setMinLength(4)
            .setMaxLength(10)
            .setRequired(true)
            .setPlaceholder("Example: Bedwars, Skyblock, Skywars")
        ])
        
          showModal(modal, {
            client: client,
            interaction: interaction
          });
      },
}
```

**Comment by Mateo-tem** [comment]
**Thanks to open this issue!**

Nope, Discord API only supports 5 Action Rows (contain Text Inputs) per modal. See [this](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal).

![image](https://media.discordapp.net/attachments/910547379617402960/957428333430325308/unknown.png)

**Comment by dubfib** [comment]
Oh okay that kinda sucks though but thanks!
