### ISSUE TITLE
"Cannot read properties of undefined (reading '0')" inside modal structure

### ISSUE THREAD

**Issue by Myzumi** [Mateo-tem/discord-modals#79]
Hi,

after the issue have been fixed in #74 i've tried to send the modal over, that worked but right after im seeing the modal, discord-modals gives an error in the mapping array (this is only an error on the bot side, nothing wrong happening on discord or anything), while it still shows fine, the error should not happen.

Error:

```
Generated Modal
Sended Modal
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading '0')
    at /home/container/node_modules/discord-modals/src/structures/Modal.js:42:96
    at Array.map (<anonymous>)
    at new Modal (/home/container/node_modules/discord-modals/src/structures/Modal.js:42:40)
    at showModal (/home/container/node_modules/discord-modals/src/structures/ShowModal.js:66:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading '0')
    at /home/container/node_modules/discord-modals/src/structures/Modal.js:42:96
    at Array.map (<anonymous>)
    at new Modal (/home/container/node_modules/discord-modals/src/structures/Modal.js:42:40)
    at showModal (/home/container/node_modules/discord-modals/src/structures/ShowModal.js:66:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
    
At the top the "Generated Modal" and "Sended Modal" should only be a reference at when it happens
Full code of the Modal: https://pastebin.com/aXhG3Kqb
Im using both latest version of discord.js and discord-modals

**Comment by Mateo-tem** [comment]
I hope this is solved, was fixed in Discord-Modals v1.3.8.
