### ISSUE TITLE
wont build my bot

### ISSUE THREAD

**Issue by Hackx2** [Mateo-tem/discord-modals#85]
Error: Cannot find module 'discord-api-types/v9'
Require stack:
- C:\Users\William\Desktop\HackBot-js\node_modules\discord-modals\src\structures\Interaction.js    
- C:\Users\William\Desktop\HackBot-js\node_modules\discord-modals\src\structures\ModalSubmitInteraction.js
- C:\Users\William\Desktop\HackBot-js\node_modules\discord-modals\index.js
- C:\Users\William\Desktop\HackBot-js\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Users\William\Desktop\HackBot-js\node_modules\discord-modals\src\structures\Interaction.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\William\\Desktop\\HackBot-js\\node_modules\\discord-modals\\src\\structures\\Interaction.js',
    'C:\\Users\\William\\Desktop\\HackBot-js\\node_modules\\discord-modals\\src\\structures\\ModalSubmitInteraction.js',
    'C:\\Users\\William\\Desktop\\HackBot-js\\node_modules\\discord-modals\\index.js',
    'C:\\Users\\William\\Desktop\\HackBot-js\\main.js'
  ]

**Comment by lupus0802** [comment]
You need the package `discord-api-types` for the modals to work, basically just do
```
npm i discord-api-types
```
in a terminal in the root folder of your project to install it.

**Comment by PabloRNC** [comment]
This is for issues of discord-modals not discord.js issues or even other issues
